#!/bin/bash

#Convert Fahrenheit to C

read -p "Converting into Fahrenheit or Celsius? f/c: " TARGET

if [ $TARGET == "f" -o $TARGET == "F" ]; then
    read -p "What is the temperature in Celsius: " CTEMP
    let FTEMP=($CTEMP*9/5)+32
    echo "The approximate temp in Celsius is $FTEMP"


elif [ $TARGET == "c" -o $TARGET == "C" ]; then
    read -p "What is the temperature in Fahrenheit: " FTEMP
    let CTEMP=($FTEMP-32)*5/9
    echo "The approximate temp in Celsius is $CTEMP"

else
    echo "Make a valid selection"

fi
